---

#The location of the Git repo containing the CA code
#Note: If this is a protected repository you will need to make it ssh accessible, and populate the ssh directory in group_vars with an appropriate deployment key and known hosts file
pyca_repo_location: http://github.com/lkiesow/pyCA.git

#The parent directory for pyCA
pyca_base_dir: "{{mh_parent_dir}}/pyCA"
#Where to store pyCA's logs
pyca_log_dir: "/var/log/matterhorn/pyCA"

#The pyCA admin username
pyca_username: admin
#The pyCA admin password
pyca_password: opencast
