---

- name: Install Java
  apt: pkg=openjdk-7-jdk update_cache=yes state=present
  sudo: yes

- name: Install Git
  apt: pkg=git-core state=present
  sudo: yes

- name: Install unzip
  apt: pkg=unzip state=present
  sudo: yes

- include: ../../common/tasks/create_tools_bin.yml

- name: Fix MH parent dir permissions
  file: path={{mh_tools_dir}}/ owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory recurse=true
  sudo: true

  #Mount NFS
- include: ../../common/tasks/nfs_mount_ro.yml

- include: ../../common/tasks/clone_mh.yml

#TODO: Modernize this/rip this out once we switch away from Solr
- name: Downloading Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.5-beta/bin/apache-tomcat-7.0.5.zip
           dest={{mh_tool_archive_dir}}/apache-tomcat-7.0.5.zip
           force=no
           mode=0644

- name: Unzipping Tomcat
  unarchive: src={{mh_tool_archive_dir}}/apache-tomcat-7.0.5.zip dest={{mh_tools_dir}} copy=no
            creates={{tomcat_dir}}

- name: Downloading Solr
  get_url: url=http://archive.apache.org/dist/lucene/solr/1.4.1/apache-solr-1.4.1.zip
           dest={{mh_tool_archive_dir}}/apache-solr-1.4.1.zip
           force=no
           mode=0644

- name: Unzipping Solr
unarchive: src={{mh_tool_archive_dir}}/apache-solr-1.4.1.zip dest={{mh_tools_dir}} copy=no
            creates={{mh_tools_dir}}/apache-solr-1.4.1

- name: Checking if Solr exists
  stat: path=/etc/init.d/solr
  register: solrpresent

- name: Stopping Solr
  service: name=solr state=stopped
  sudo: yes
  when: solrpresent.stat.exists is defined and solrpresent.stat.exists == True

- name: Clearing old Solr data
  file: path={{solr_data_dir}} state=absent

- name: Clearing old Solr webapp
  file: path={{tomcat_dir}}/webapps/solr state=absent

- name: Applying Solr to Tomcat
  shell: unzip apache-solr-1.4.1/example/webapps/solr.war -d apache-tomcat-7.0.5/webapps/solr
         chdir={{mh_tools_dir}}
         creates=apache-tomcat-7.0.5/webapps/solr

- name: Copying Engage search index
  shell: cp -rv {{mh_base_dir}}/modules/matterhorn-search-service-impl/src/main/resources/solr {{solr_data_dir}}
         chdir={{mh_tools_dir}}

- name: Creating lib directory
  file: path={{solr_data_dir}}/lib owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory

- name: Copying required Solr jar
  shell: cp -rv {{m2_repo}}/org/opencastproject/matterhorn-solr/{{mh_pom_version}}/matterhorn-solr-{{mh_pom_version}}.jar {{solr_data_dir}}/lib
         chdir={{mh_tools_dir}}

- name: Configure Tomcat
  template: src=server.xml dest={{mh_tools_dir}}/apache-tomcat-7.0.5/conf/

- name: Configure Solr
  template: src=solrconfig.xml dest={{solr_data_dir}}/conf/

- name: Creating Tomcat configuration directory
  file: path={{mh_tools_dir}}/apache-tomcat-7.0.5/conf/Catalina/localhost/ owner="{{matterhorn_user}}" group="{{matterhorn_group}}" state=directory

- name: Configure Tomcat Solr configuration
  template: src=solr.xml dest={{mh_tools_dir}}/apache-tomcat-7.0.5/conf/Catalina/localhost/

- name: Creating Solr init script
  template: src=solr-init.sh dest=/etc/init.d/solr
  sudo: yes

- name: Fix init script file permissions
  file: path=/etc/init.d/solr mode=0755
  sudo: yes

- name: Fix Tomcat script file permissions
  shell: chmod 0755 {{mh_tools_dir}}/apache-tomcat-7.0.5/bin/*.sh

- name: Setting Solr to start on boot
  service: name=solr state=stopped enabled=yes
  sudo: yes
