---

admin:
  - "opencast-{{ oc_package_version }}-common"
  - "opencast-{{ oc_package_version }}-admin"

adminpresentation:
  - "opencast-{{ oc_package_version }}-common"
  - "opencast-{{ oc_package_version }}-adminpresentation"

allinone:
  - "opencast-{{ oc_package_version }}-common"
  - "opencast-{{ oc_package_version }}-allinone"

ingest:
  - "opencast-{{ oc_package_version }}-common"
  - "opencast-{{ oc_package_version }}-ingest"

presentation:
  - "opencast-{{ oc_package_version }}-common"
  - "opencast-{{ oc_package_version }}-presentation"

worker:
  - "opencast-{{ oc_package_version }}-common"
  - "opencast-{{ oc_package_version }}-worker"
  - "ffmpeg-dist"
