---

- include: ../../common/tasks/clone_mh.yml

- include: ../../common/tasks/create_tools_bin.yml

- name: Downloading ActiveMQ
  get_url: url=http://archive.apache.org/dist/activemq/{{activemq_version}}/apache-activemq-{{activemq_version}}-bin.tar.gz
           dest={{mh_tool_archive_dir}}/apache-activemq-{{activemq_version}}-bin.tar.gz
           force=no

- name: Decompressing ActiveMQ
  unarchive: src={{mh_tool_archive_dir}}/apache-activemq-{{activemq_version}}-bin.tar.gz dest={{mh_tools_dir}} copy=no

- name: Configuring ActiveMQ user
  shell: sed -i 's/^ACTIVEMQ_USER=""/ACTIVEMQ_USER="{{activemq_user}}"/' {{activemq_home_dir}}/bin/env

- name: Configuring ActiveMQ group
  shell: echo 'ACTIVEMQ_GROUP="{{activemq_group}}"' >> {{activemq_home_dir}}/bin/env

- name: Configuring ActiveMQ home location
  shell: echo 'ACTIVEMQ_HOME="{{activemq_home_dir}}"' >> {{activemq_home_dir}}/bin/env

- name: Creating ActiveMQ data directory
  file: path={{activemq_data_dir}} owner={{activemq_user}} group={{activemq_group}} state=directory
  sudo: yes

- name: Configuring ActiveMQ data location
  shell: echo 'ACTIVEMQ_DATA="{{activemq_data_dir}}"' >> {{activemq_home_dir}}/bin/env

- name: Creating ActiveMQ log directory
  file: path={{activemq_log_dir}} owner={{activemq_user}} group={{activemq_group}} state=directory
  sudo: yes

#TODO make sure this and other activeMQ data are in sane locations
- name: Configuring ActiveMQ log location
  shell: echo 'ACTIVEMQ_LOG="{{activemq_log_dir}}"' >> {{activemq_home_dir}}/bin/env

- name: Linking ActiveMQ global variables
  file: src={{activemq_home_dir}}/bin/env dest=/etc/default/activemq state=link
  sudo: yes

- name: Applying ActiveMQ configuration
  shell: cp -rv {{mh_base_dir}}/docs/scripts/activemq/activemq.xml {{activemq_home_dir}}/conf/

- name: Installing ActiveMQ init script
  file: src={{activemq_home_dir}}/bin/activemq dest=/etc/init.d/activemq state=link
  sudo: yes

- name: Setting ActiveMQ to start on boot
  service: name=activemq enabled=yes
  sudo: yes
