---

- name: Checking if nginx exists
  stat: path=/etc/init.d/nginx
  register: nginxpresent

- name: Starting nginx
  service: name=nginx state=started
  when: nginxpresent.stat.exists is defined and nginxpresent.stat.exists == True
  sudo: yes
