---

- name: Install Python
  apt: pkg=python2.7 update_cache=yes state=present
  sudo: yes

- name: Install Pip
  apt: pkg=python-pip state=present
  sudo: yes

#- name: Install Python Virtualenv
#  apt: pkg=python-virtualenv state=present
#  sudo: yes

- name: Install Python Dev
  apt: pkg=python-dev state=present
  sudo: yes

- name: Install libcurl
  apt: pkg=libcurl4-gnutls-dev state=present
  sudo: yes

- name: Install Git
  apt: pkg=git-core state=present
  sudo: yes

- name: Create pyCA parent dir
  file: path={{mh_parent_dir}}/ owner={{matterhorn_user}} group={{matterhorn_user}} state=directory recurse=true
  sudo: yes

- name: Create pyCA log dir
  file: path={{pyca_log_dir}} owner={{matterhorn_user}} group={{matterhorn_user}} state=directory recurse=true
  sudo: yes

- name: Pushing SSH configs
  copy: src=../../../group_vars/ssh/ dest=/home/{{matterhorn_user}}/.ssh mode=600

- name: Checkout pyCA
  git: repo={{pyca_repo_location}}
       dest={{pyca_base_dir}}
       update=yes
       force=yes

#- name: Creating pyCA virtualenv
#  shell: virtualenv env
#         chdir={{pyca_base_dir}}

- name: Installing required Python modules
  shell: pip install -r requirements.txt
         chdir={{pyca_base_dir}}
  sudo: yes

- name: Templating pyCA config file
  template: src=pyca.conf dest={{pyca_base_dir}}/etc/

- name: Templating pyCA init file
  template: src=pyca.sh dest=/etc/init.d/pyca mode=755
  sudo: yes
