---

- name: Install MySQL server
  apt: pkg=mysql-server state=present
  sudo: yes

- name: Install Python MySQL bindings
  apt: pkg=python-mysqldb state=present
  sudo: yes

- name: MySQL ROOT Dumping DB
  mysql_db: name={{db_schema}} login_user=root login_password= state=absent
  ignore_errors: yes

- name: MySQL ROOT Creating DB
  mysql_db: name={{db_schema}} login_user=root login_password= state=present encoding="utf8" collation="utf8_general_ci"

- name: MySQL ROOT Granting user permissions on DB
  mysql_user: login_user=root login_password= name={{db_user}} password={{db_pass}} host="localhost" priv="{{db_schema}}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX"
